
#ifndef GLOBALS_H
#define GLOBALS_H

enum IFCU_ENUMS {
  IFCU_ON,
  IFCU_OFF,
  IFCU_MODE_AUTO_COOL,
  IFCU_MODE_MANUAL_COOL,
  IFCU_MODE_FAN_ONLY,
  IFCU_MODE_AUTO_HEAT,
  IFCU_MODE_MANUAL_HEAT,
  IFCU_FAN_SPEED_LOW,
  IFCU_FAN_SPEED_MEDIUM,
  IFCU_FAN_SPEED_HIGH,
  IFCU_FAN_SPEED_TEN_SPEED,
  IFCU_ACTION_INCREASE_TEMP,
  IFCU_ACTION_DECREASE_TEMP,
};

#endif
