#ifndef SystemEnums_h
#define SystemEnums_h

enum SYSTEM_MODE {
  MODE_RUNNING,
  MODE_STOPPED,
  MODE_BYPASS,
};

enum SYSTEM_STATUS {
  STATUS_RUNNING,
  STATUS_STOP_BY_AMBIENT_TEMP,
  STATUS_STOP_BY_STATION_TEMP,
  STATUS_STOP_BY_CURRENT,
};

#endif
