#ifndef SystemEnums_h
#define SystemEnums_h

enum SYSTEM_MODE {
  MODE_RUNNING,
  MODE_STOPPED,
  MODE_BYPASS,
  MODE_SIMULATION,
};

enum SIMULATION_STATUS {  // for MODE_SIMULATION only
  STATUS_RUNNING,
  STATUS_STOPPED,
  STATUS_STOP_BY_AMBIENT_TEMP,
  STATUS_STOP_BY_STATION_TEMP,
  STATUS_STOP_BY_CURRENT,
};

#endif
