#ifndef SystemEnums_h
#define SystemEnums_h

#define CONST_LONGER_THRESHOLED 900
#define CONST_SHORTER_THRESHOLED 550
#define CONST_ESCAPE_BUFFER 100

enum SystemStatus {
  SYS_INIT,
  SYS_STARTING,
  SYS_RUNNING,
  SYS_STOPPED,
  SYS_ALLOW_10S,
  SYS_FAILURE
};

const char* STATUS_STR[] = { "SYS_INIT", "SYS_STARTING", "SYS_RUNNING", "SYS_STOPPED", "SYS_ALLOW_10S", "SYS_FAILURE" };

enum TrafficStatus {
  TRAFFIC_OFF,
  TRAFFIC_RED,
  TRAFFIC_YELLOW,
  TRAFFIC_GREEN
};

enum DisplayState {
  DISPLAY_INIT,
  DISPLAY_SYS_RUNNING,
  DISPLAY_SYS_STOPPED,
  DISPLAY_SYS_COUNTDOWN_0,
  DISPLAY_SYS_COUNTDOWN_1,
  DISPLAY_SYS_COUNTDOWN_2,
  DISPLAY_SYS_COUNTDOWN_3,
  DISPLAY_SYS_COUNTDOWN_4,
  DISPLAY_SYS_COUNTDOWN_5,
  DISPLAY_SYS_COUNTDOWN_6,
  DISPLAY_SYS_COUNTDOWN_7,
  DISPLAY_SYS_COUNTDOWN_8,
  DISPLAY_SYS_COUNTDOWN_9,
  DISPLAY_SENSOR_UNHEALTHY,
  DISPLAY_IOT_CSQ,
  DISPLAY_IOT_CGATT,
};


#endif
