#ifndef SystemEnums_h
#define SystemEnums_h

#define CONST_LONGER_THRESHOLED 900
#define CONST_SHORTER_THRESHOLED 550
#define CONST_ESCAPE_BUFFER 100

enum SystemStatus {
  SYS_INIT,
  SYS_STARTING,
  SYS_RUNNING,
  SYS_STOPPED,
  SYS_ALLOW_10S,
  SYS_FAILURE
};

const char* STATUS_STR[] = { "SYS_INIT", "SYS_STARTING", "SYS_RUNNING", "SYS_STOPPED", "SYS_ALLOW_10S", "SYS_FAILURE" };

enum TrafficStatus {
  TRAFFIC_OFF,
  TRAFFIC_RED,
  TRAFFIC_YELLOW,
  TRAFFIC_GREEN
};

enum DisplayState {
  NULL_PLACEHOLDER,
  DISPLAY_SYS_INIT,
  DISPLAY_SYS_RUNNING,
  DISPLAY_SYS_DETECTED_0,
  DISPLAY_SYS_DETECTED_1,
  DISPLAY_SYS_DETECTED_2,
  DISPLAY_SYS_DETECTED_3,
  DISPLAY_SYS_DETECTED_4,
  DISPLAY_SYS_DETECTED_5,
  DISPLAY_SYS_DETECTED_6,
  DISPLAY_SYS_DETECTED_7,
  DISPLAY_SYS_DETECTED_8,
  DISPLAY_SYS_DETECTED_9,
  DISPLAY_SYS_STOPPED,
  DISPLAY_SYS_COUNTDOWN_0,
  DISPLAY_SYS_COUNTDOWN_1,
  DISPLAY_SYS_COUNTDOWN_2,
  DISPLAY_SYS_COUNTDOWN_3,
  DISPLAY_SYS_COUNTDOWN_4,
  DISPLAY_SYS_COUNTDOWN_5,
  DISPLAY_SYS_COUNTDOWN_6,
  DISPLAY_SYS_COUNTDOWN_7,
  DISPLAY_SYS_COUNTDOWN_8,
  DISPLAY_SYS_COUNTDOWN_9,
  DISPLAY_SENSOR_UNHEALTHY,
  DISPLAY_IOT_INIT,
  DISPLAY_IOT_FINISH_GET_IP,
  DISPLAY_IOT_FINISH_GET_IMEI,
  DISPLAY_IOT_FINISH_GET_CSQ,
  DISPLAY_IOT_FINISH_GET_CGATT,
  DISPLAY_IOT_FINISH_OPEN,
  DISPLAY_IOT_FINISH_CONN,
  DISPLAY_IOT_CSQ,
  DISPLAY_IOT_CGATT,
};

enum PublishState {
  NULL_PUBLISH_STATE,
  PUBLISH_REGULAR,
  PUBLISH_DETECTED,
  PUBLISH_ESCAPED,
};


#endif
